language: java

jdk: oraclejdk8

script: mvn clean verify

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service acpid stop
  - sudo service atd stop
  - sudo service cron stop
  - sudo service memcached stop
  - sudo service ntp stop
  - sudo service rabbitmq-server stop
  - sudo service resolvconf stop
  - sudo service sshguard stop
  - sudo service ssh stop
  - sudo service rsyslog stop
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then openssl aes-256-cbc -K $encrypted_28b5c6ae7982_key -iv $encrypted_28b5c6ae7982_iv -in settings-central.tar.enc -out settings-central.tar -d && tar -xf settings-central.tar ; fi

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn -s ./settings.xml deploy -Dexternal -DtrimStackTrace=false; else mvn verify -DtrimStackTrace=false; fi
